apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: webapp
spec:
  containers:
    - name: webapp-images
      image: 792411911957.dkr.ecr.us-east-1.amazonaws.com/webapp-images:v0.1
      env:
        - name: DBPWD
          value: marco
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local" # hostname of the dabase server
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080