apiVersion: v1
kind: Pod
metadata:
  name: sqldb-pod
  namespace: sqldb
spec:
  containers:
    - name: sqldb-images
      image: 792411911957.dkr.ecr.us-east-1.amazonaws.com/sqldb-images:v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306